### ISSUE TITLE
Get vocal data

### ISSUE THREAD

**Issue by Umbaji001** [Umbaji/NMT-Melinda--Dataset#1]

**Comment by Umbaji001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get vocal data](https://trello.com/c/LkJDSVaC/1-get-vocal-data)

**Comment by Henrietta-PM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generate a docker container file for automatic data generation](https://trello.com/c/Fci2aJ2V/2-generate-a-docker-container-file-for-automatic-data-generation)
